---
- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

#####################################################################
# Redis nodes: open 6379 but ONLY for allowed_redis_clients_cidr
# and allowed_cluster_cidr
#####################################################################

- name: Allow application/client access to Redis TCP {{ redis_port }} from allowed_redis_clients_cidr
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ allowed_redis_clients_cidr }}" port port="{{ redis_port }}" protocol="tcp" accept'
    permanent: yes
    state: enabled
    immediate: yes
  when:
    - role_mode == "server" or (deploy_redis | default(false) | bool)

- name: Allow internal cluster access to Redis TCP {{ redis_port }} from allowed_cluster_cidr
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ allowed_cluster_cidr }}" port port="{{ redis_port }}" protocol="tcp" accept'
    permanent: yes
    state: enabled
    immediate: yes
  when:
    - role_mode == "server" or (deploy_redis | default(false) | bool)

#####################################################################
# Sentinel nodes: open 26379 but ONLY for cluster CIDR
#####################################################################

- name: Allow Sentinel TCP {{ sentinel_port }} from internal cluster CIDR
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="{{ allowed_cluster_cidr }}" port port="{{ sentinel_port }}" protocol="tcp" accept'
    permanent: yes
    state: enabled
    immediate: yes
  when:
    - role_mode == "sentinel" or (deploy_sentinel | default(false) | bool)

#####################################################################
# Reload firewalld so rules persist
#####################################################################

- name: Reload firewalld to apply rules
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false 

