- name: Prepare all nodes (java, users, directories)
  hosts: all
  roles:
    - common
    - certs

- name: Install and configure ZooKeeper ensemble (3 nodes)
  hosts: zk_nodes
  roles:
    - zookeeper

- name: Install and configure Kafka brokers (6 nodes)
  hosts: kafka_nodes
  roles:
    - kafka
    - monitoring
