---
- name: Setup Redis data nodes (master + replicas)
  hosts: redis_nodes
  become: true
  roles:
    - role: redis
      vars:
        role_mode: "server"
        deploy_sentinel: false

- name: Setup Sentinel nodes (monitor + failover)
  hosts: sentinel_nodes
  become: true
  roles:
    - role: redis
      vars:
        role_mode: "sentinel"
        deploy_redis: false
