---
- name: Ensure firewalld is installed
  package:
    name: firewalld
    state: present

- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open RabbitMQ ports
  firewalld:
    immediate: true
    permanent: true
    state: enabled
    port: "{{ item }}"
  loop: "{{ rabbitmq_ports }}"
