---
- name: Ensure base packages present
  package:
    name:
      - dnf-plugins-core
      - logrotate
      - socat
      - curl
      - rsync
    state: present

- name: Download Package Erlang 
  get_url:
    url: https://packagecloud.io/rabbitmq/erlang/packages/el/9/erlang-26.2.5.4-1.el9.x86_64.rpm/download.rpm?distro_version_id=240 
    dest: /tmp/erlang-26.2.5.4-1.el9.x86_64.rpm
    mode: '0644'
- name: Install Package Erlang
  yum:
    name: /tmp/erlang-26.2.5.4-1.el9.x86_64.rpm
    state: present
    disable_gpg_check: yes
- name: Download Package RabbitMQ Server 
  get_url:
    url: https://packagecloud.io/rabbitmq/rabbitmq-server/packages/el/9/rabbitmq-server-3.13.7-1.el8.noarch.rpm/download.rpm?distro_version_id=240 
    dest: /tmp/rabbitmq-server-3.13.7-1.el8.noarch.rpm
    mode: '0644'
- name: Install Package RabbitMQ Server 
  yum:
    name: /tmp/rabbitmq-server-3.13.7-1.el8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Enable rabbitmq-server service
  service:
    name: "{{ rabbitmq_service_name }}"
    enabled: true
