---
- name: Ensure base packages present
  package:
    name:
      - dnf-plugins-core
      - logrotate
      - socat
      - curl
      - rsync
    state: present

- name: Add Erlang repo (Cloudsmith)
  yum_repository:
    name: "{{ rabbitmq_erlang_repo_name }}"
    description: "Erlang (Cloudsmith) for RabbitMQ"
    baseurl: "{{ rabbitmq_erlang_repo_baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ rabbitmq_erlang_repo_gpgkey }}"
    module_hotfixes: yes

- name: Add RabbitMQ server repo (Cloudsmith)
  yum_repository:
    name: "{{ rabbitmq_server_repo_name }}"
    description: "RabbitMQ Server (Cloudsmith)"
    baseurl: "{{ rabbitmq_server_repo_baseurl }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ rabbitmq_server_repo_gpgkey }}"
    module_hotfixes: yes

- name: Install Erlang and RabbitMQ
  package:
    name:
      - erlang
      - rabbitmq-server-{{ rabbitmq_version }}
    state: present

- name: Enable rabbitmq-server service
  service:
    name: "{{ rabbitmq_service_name }}"
    enabled: true
